export const products = [
  {
    _id: "1",
    name: "Airpods Wireless Bluetooth Headphones",
    image: "https://unsplash.com/photos/xaKEDwvfuGI",
    description:
      "Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working",
    brand: "Apple",
    category: "Electronics",
    price: 50000,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "iPhone 11 Pro 256GB Memory",
    image: "https://unsplash.com/photos/vI8_06RmSC0",
    description:
      "Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life",
    brand: "Apple",
    category: "Electronics",
    price: 120000,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: "3",
    name: "Cannon EOS 80D DSLR Camera",
    image: "https://unsplash.com/photos/ZVYiusqnrTQ",
    description:
      "Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design",
    brand: "Cannon",
    category: "Electronics",
    price: 350000,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: "4",
    name: "Sony Playstation 4 Pro White Version",
    image: "https://unsplash.com/photos/gGgoDJRD2WM",
    description:
      "The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music",
    brand: "Sony",
    category: "Electronics",
    price: 150000,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "iphone",
    image: "https://unsplash.com/photos/skoebzCO9tc",
    description:
      "Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience",
    brand: "Logitech",
    category: "Electronics",
    price: 5000,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: "6",
    name: "Mac book pro",
    image: "https://unsplash.com/photos/Dy9-5TvjuWs",
    description:
      "Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space",
    brand: "Amazon",
    category: "Electronics",
    price: 2500,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: "7",
    name: "Airpods Wireless Bluetooth Headphones",
    image: "https://unsplash.com/photos/xaKEDwvfuGI",
    description:
      "Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working",
    brand: "Apple",
    category: "Electronics",
    price: 50000,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "8",
    name: "iPhone 11 Pro 256GB Memory",
    image: "https://unsplash.com/photos/vI8_06RmSC0",
    description:
      "Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life",
    brand: "Apple",
    category: "Electronics",
    price: 120000,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: "9",
    name: "Cannon EOS 80D DSLR Camera",
    image: "https://unsplash.com/photos/ZVYiusqnrTQ",
    description:
      "Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design",
    brand: "Cannon",
    category: "Electronics",
    price: 350000,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: "10",
    name: "Sony Playstation 4 Pro White Version",
    image: "https://unsplash.com/photos/gGgoDJRD2WM",
    description:
      "The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music",
    brand: "Sony",
    category: "Electronics",
    price: 150000,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: "11",
    name: "iphone",
    image: "https://unsplash.com/photos/skoebzCO9tc",
    description:
      "Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience",
    brand: "Logitech",
    category: "Electronics",
    price: 5000,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: "12",
    name: "Mac book pro",
    image: "https://unsplash.com/photos/Dy9-5TvjuWs",
    description:
      "Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space",
    brand: "Amazon",
    category: "Electronics",
    price: 2500,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
];


// export default products;
